ALTER TABLE posts ADD COLUMN IF NOT EXISTS title_size real NOT NULL DEFAULT 72;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS subtitle_size real NOT NULL DEFAULT 28;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS body_size real NOT NULL DEFAULT 20;
